version: '3.8'

services:
  backend:
    build: ./backend
    image: blackbox-backend:latest  # Explicitly name the local image
    ports:
      - "8000:8000"
    command: ["-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build: ./frontend
    image: blackbox-frontend:latest # Explicitly name the local image
    ports:
      - "8080:3000"
    depends_on:
      - backend